### ISSUE TITLE
need the last compiled DLL

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/SynFTP#117]
@tbeu  Thanks for your previous help. Now I can see you deleted the repo. I need the last compiled version (I didn';t find it in my HDD yet), maybe you can send it to me?
I wanted to update Synwrite a little.

**Comment by tbeu** [comment]
I am afraid I no longer have the build environment available after I migrated to new PC with Win10. I also did not find SynFtp.dll. Latest build should be from October 2018.
