### ISSUE TITLE
'how-to-build' file

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/SynFTP#86]
rival has Building file. can we have it? @tbeu (Pls detailed as I don't use MSVS at all(

**Comment by tbeu** [comment]
Sure can do it .. later.

**Comment by tbeu** [comment]
Will do it once a new OpenSSL version is released.

**Comment by Alexey-T** [comment]
okay

**Comment by tbeu** [comment]
OpenSSL 1.0.1k is now available, including bug and security fixes

**Comment by Alexey-T** [comment]
gut

**Comment by Alexey-T** [comment]
good to have a file.

**Comment by tbeu** [comment]
Please wait, it is not yet finished.
