### ISSUE TITLE
Api cmd "connect to"

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/SynFTP#88]
I was asked. so i post it, here, what @tbeu  thinks?
SW can has command (keys list): "connect to site 1", "connect to site 2".... "connect to site 9"-- it can handle em like this: it sends via API to FTP : action, with new name, and FTP 1st disconnects (if connected), then it searches for account starting with "1" ... "9", then it connects to it. This way user can press Alt+F1 and connect to accnt "1. mysitename", Alt+F2 connect to "2. my other site"

**Comment by Alexey-T** [comment]
@tbeu , thanks for patches. What do u think.

**Comment by tbeu** [comment]
Profiles are stored in SynFTP.xml and displayed in Connect popup in alpha-numeric order (with numbers first). This is OK. But there is no strong mapping from site number to profile name. In Connect popup we should add the site numbers starting by 1 to give some feedback to user.

**Comment by Alexey-T** [comment]
hm, u didn't see idea. Idea: I can name profile not "mysite" but "4. mysite" (leading digit "4" or "1" to "9"). if i name profile "4. mysite" then Syn user can call command "Connect to profile 4" and SynFTP quickly disconnects, finds this profile, and connects to it.

SW user can have 9 hotkeys - "connect to profile 1.... to profile 9".
He can quicky rename profiles. 
If he renames profile "lala" to "2. lala" then hotkey "connect to profile 2" uses this profile "2. lala"

**Comment by tbeu** [comment]
This is a bloody hack! Why not do it the proper way and a assign key combinations (see Options->Customize->Keys) to new command "Connect to profile mysite"? You know where SynFTP.xml is located.

**Comment by Alexey-T** [comment]
if uses has 50 profiles, then SW  can give 50 hotkeys?? No. It cannot. It can give eg. 9 hotkeys. So this hack needed
Also it needed because it's bad to read profile names (SW must not read any XML files from plugin)

**Comment by Alexey-T** [comment]
What i want are commands

- connect to profile "1" ... "9" (to profiles starting from "1".."9")
- disconnect from ftp
- upload current file to current ftp
- download+open curr file
- call "Goto folder" dlg

so I can make new group in SW keys

**Comment by tbeu** [comment]
Yes, that is fine. I only do not like the hack with the leading numbers in the profile. This does not sound mature to me. In TC you have CTRL+F to display connection selection/edit dialog.

**Comment by Alexey-T** [comment]
hm, how is other way can be done. To quick connect to any ftp

**Comment by tbeu** [comment]
What if hot-key command takes an additional parameter profile name. This must be the same as in SynFTP.xml but is not read from there.

**Comment by Alexey-T** [comment]
2 actions maybe good

- connect to profile <name_from_action_param>
- get names of all profiles (\n separated str)

**Comment by Alexey-T** [comment]
Maybe 2 actions:

- connect to profile name (name passed via action, e.g. A1, A2, A3 - one of)
- get names of profiles (e.g. A2 points to buffer, A1 is buffer size)

**Comment by tbeu** [comment]
At which time will SynW ask for list of profiles names? Immediately before connect cmd? Or at time of hot key config?

**Comment by Alexey-T** [comment]
hm. Before connect cmd. (key config won't show profile names)

**Comment by Alexey-T** [comment]
logic "find profile with 1 char" will be in SW.

**Comment by Alexey-T** [comment]
Lets have such acctions
(example is https://sourceforge.net/p/synwrite/wiki/cActionGetOpenedFileName/ )

cActionFtpGetProfiles
A1 (PWideChar) - points to WideChar buffer to store profilenames \n-separated. 
A2 (int) - Buffer size in characters 

cActionFtpConnect
A1 (Pwidechar) -Points to Widechar string of profile name. Ftp must disconnect and connect this this profile

cActionFtpDisconnect
no param usage

**Comment by Alexey-T** [comment]
cActionFtpGetProfiles = "FtpGetProfiles"
     cActionFtpConnect = "FtpConnect"
     cActionFtpDisconnect = "FtpDisconnect"
 
later others from above.
If action gives ok result (profile found for Connect) then return cSynOK else cSynError

**Comment by tbeu** [comment]
Yes, API is Ok. Not sure where SynW will display and store profile names retrieved by cActionFtpGetProfiles?

**Comment by Alexey-T** [comment]
Commd "Connect to FTP" shows later list of profiles- like TC

**Comment by tbeu** [comment]
Will need some time to do it. Pretty busy now.

**Comment by Alexey-T** [comment]
Failed to deliver to 'su...@tbeu.de'
SMTP module(domain tbeu.de) reports:
 host mail.tbeu.de says:
 553 sorry, that domain isn't in my list of allowed rcpthosts (#5.7.1)

**Comment by tbeu** [comment]
Sorry, account tbeu.de was closed by hoster :angry:. Hope to have it working again soon.

**Comment by Alexey-T** [comment]
I told in mail: I updated AStyle plugin --it's with PYD ok file
