### ISSUE TITLE
ColorPickr

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/SynFTP#96]
@tbeu : NPP has nice colorpicker: it's GUI nice form https://code.google.com/p/nppqcp/
Is easy to make Exe from it?
Exe which gets color parameter (int) and returns exitcode (color value).

**Comment by tbeu** [comment]
Need to check it.
Can you make a new repo for it? It is different from SynFTP project.

**Comment by Alexey-T** [comment]
-Can you make a new repo for i

 maybe u do? It's cpp code, you fill it?

**Comment by tbeu** [comment]
OK.

**Comment by tbeu** [comment]
Yes, should be easy. It already is MSVC project.

**Comment by Alexey-T** [comment]
good!Can make new Color pk

**Comment by tbeu** [comment]
Thought it would be a quick kack but it is all based on messages.

**Comment by Alexey-T** [comment]
hm,bad. Ok I have my picker..
